app_todos/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import redirect_to_todos

app_name = "todo_app"
urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls"), name="todos"),
    path("", redirect_to_todos, name="app_index"),
]

handler400 = "app_todos.views.not_found"

handler500 = "app_todos.views.interval_error"

todos/urls.py
from django.urls import path
from .views import (
    LogOut,
    TodosListView,
    AddTodo,
    EditTodo,
    TodoDetails,
    TodoDelete,
    UserCreate,
    UserActiveAccount,
    UserNewCode,
    UserLogin,
    UserFactAuth,
    UserNewCodeFactor,
    ResetPasswordView,
    NewPasswordView,
)

app_name = "todo_list"
urlpatterns = [
    path("", TodosListView.as_view(), name="index"),
    path("add", AddTodo.as_view(), name="add_todo"),
    path("edit/<uuid:id>", EditTodo.as_view(), name="edit_todo"),
    path("details/<uuid:pk>", TodoDetails.as_view(), name="details_todo"),
    path("delete/<uuid:id>", TodoDelete.as_view(), name="delete_todo"),
    path("account", UserCreate.as_view(), name="todo_user_account"),
    path(
        "active/account", UserActiveAccount.as_view(), name="todo_user_active_account"
    ),
    path("new/code", UserNewCode.as_view(), name="todo_user_new_code"),
    path("login", UserLogin.as_view(), name="todo_user_login"),
    path("fact/auth", UserFactAuth.as_view(), name="todo_user_fact_auth"),
    path(
        "code/fact/auth",
        UserNewCodeFactor.as_view(),
        name="todo_user_new_code_fact_auth",
    ),
    path(
        "reset/password",
        ResetPasswordView.as_view(),
        name="todo_user_reset_password",
    ),
    path("newpassword", NewPasswordView.as_view(), name="todo_user_new_password"),
    path("logout", LogOut.as_view(), name="logout"),
]

todos/forms.py
import re
from django.forms import ModelForm

from .models import Todo, UserTodo, FactorAuth


class TodoForm(ModelForm):
    class Meta:
        model = Todo
        exclude = ["created_at", "updated_at", "deleted_at", "done", "user_id"]


class EditTodoForm(ModelForm):
    class Meta:
        model = Todo
        fields = ["title", "content", "done", "expired_at"]


class UserForm(ModelForm):

    class Meta:
        model = UserTodo
        fields = ["first_name", "last_name", "email", "password"]

    rgx_password = r"^[a-zA-Z0-9]{12}$"

    def is_valid(self):
        if re.match(self.rgx_password, self.data["password"]) == None:
            self.add_error(
                "password", "password must be content 12 alphanumics characters"
            )
            super().is_valid()
            return False
        if self.data["password"] != self.data["confirm_password"]:
            self.add_error("password", "password and confirm password must be the same")
            super().is_valid()
            return False
        return super().is_valid()


class UserNewPasswordForm(ModelForm):

    class Meta:
        model = UserTodo
        fields = ["code", "password"]

    rgx_password = r"^[a-zA-Z0-9]{12}$"
    rgx_code = r"^[a-zA-Z0-9]{7,10}$"

    def is_valid(self):
        if re.match(self.rgx_password, self.data["password"]) == None:
            self.add_error(
                "password", "password must be content 12 alphanumics characters"
            )
            return False
        if self.data["password"] != self.data["confirm_password"]:
            self.add_error("password", "password and confirm password must be the same")
            return False

        if re.match(self.rgx_code, self.data["code"]) == None:
            self.add_error("code", "code invalid or expired")
            return False
        setattr(
            self,
            "cleaned_data",
            dict(code=self.data.get("code"), password=self.data.get("password")),
        )
        return True


class UserActivationForm(ModelForm):

    class Meta:
        model = UserTodo
        fields = ["code"]

    rgx_code = r"^[a-zA-Z0-9]{7,10}$"

    def is_valid(self):

        if re.match(self.rgx_code, self.data["code"]) == None:
            return False
        else:
            setattr(self, "cleaned_data", dict(code=self.data["code"]))
            return True


class UserFactAuthForm(ModelForm):

    class Meta:
        model = FactorAuth
        fields = ["code"]

    rgx_code = r"^[a-zA-Z0-9]{7,10}$"

    def is_valid(self):

        if re.match(self.rgx_code, self.data["code"]) == None:
            return False
        else:
            setattr(self, "cleaned_data", dict(code=self.data["code"]))
            return True


class UserNewCodeForm(ModelForm):

    class Meta:
        model = UserTodo
        fields = ["email"]

    rgx_email = r"^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$"

    def is_valid(self):
        if re.match(self.rgx_email, self.data["email"]) == None:
            return False
        else:
            setattr(self, "cleaned_data", dict(email=self.data["email"]))
            return True


class UserLoginForm(ModelForm):

    class Meta:
        model = UserTodo
        fields = ["email", "password"]

    rgx_email = r"^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$"

    rgx_password = r"^[a-zA-Z0-9]{12}$"

    def is_valid(self):
        if re.match(self.rgx_email, self.data["email"]) == None:
            return False
        elif re.match(self.rgx_password, self.data["password"]) == None:
            return False
        else:
            setattr(
                self,
                "cleaned_data",
                dict(email=self.data["email"], password=self.data["password"]),
            )
            return True

todos/views.py
import datetime
from django.utils import timezone
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.views.generic.detail import DetailView
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.utils import timezone
from django.core.mail import send_mail
from django.contrib import messages
from django.contrib.sessions.models import Session
from todos.services import get_todos
from django.forms.models import model_to_dict
from todos.utils import get_code, get_jwt_token
from .models import FactorAuth, ResetPassword, Todo, UserTodo
from .forms import (
    TodoForm,
    EditTodoForm,
    UserActivationForm,
    UserFactAuthForm,
    UserForm,
    UserLoginForm,
    UserNewCodeForm,
    UserNewPasswordForm,
)
import os
import bcrypt


class TodosListView(View):
    template_name = "todos/index.html"

    def get(self, request: HttpRequest):
        try:
            user_todo: dict = getattr(request, "user_todo")
            t_done = Todo.objects.filter(
                done=True, deleted_at__isnull=True, user_id__id=user_todo.get("user_id")
            )[0:100]
            t_not_done = Todo.objects.filter(
                done=False,
                deleted_at__isnull=True,
                user_id__id=user_todo.get("user_id"),
            )[0:100]

            return render(
                request,
                self.template_name,
                {
                    "todos": {
                        "todos_done": t_done,
                        "todos_not_done": t_not_done,
                    },
                    "user_name": user_todo.get("user_name"),
                },
            )
        except Exception as e:
            return render(
                request,
                "500.html",
            )


class AddTodo(View):

    template_name = "todos/add_todo.html"

    def get(self, request) -> HttpResponse:
        form_todo = TodoForm()
        return render(
            request,
            self.template_name,
            {"form_todo": form_todo, "user_name": request.user_todo.get("user_name")},
        )

    def post(self, request) -> HttpResponse | None:
        todo_form = TodoForm(request.POST)
        try:
            user_todo = request.user_todo
            if todo_form.is_valid():
                data = todo_form.cleaned_data
                todo = Todo(**data)
                todo.user_id = UserTodo.objects.get(id=user_todo.get("user_id"))
                todo.save()
                messages.success(
                    request,
                    message="todo has been created successfully. create another todo if you want",
                )
                return render(
                    request,
                    self.template_name,
                    {"user_name": request.user_todo.get("user_name")},
                )

            messages.error(
                request,
                message="invalid form data",
            )

            return render(
                request,
                self.template_name,
                {
                    "errors": todo_form.errors,
                    "todo": todo_form,
                    "user_name": request.user_todo.get("user_name"),
                },
            )

        except (ValidationError, Exception):
            messages.error(
                request,
                message="An occurred, please try again, later",
            )

            return render(
                request,
                self.template_name,
                {
                    "errors": todo_form.errors,
                    "todo": todo_form,
                    "user_name": request.user_todo.get("user_name"),
                },
            )


class EditTodo(View):

    template_name = "todos/edit_todo.html"

    def get(self, request, id) -> HttpResponse:

        todo = get_object_or_404(Todo, pk=id)
        user_todo = request.user_todo

        return render(
            request,
            self.template_name,
            {
                "todo": {
                    **model_to_dict(todo),
                    "id": id,
                    "expired_at": todo.get_expired(),
                },
                "user_name": user_todo.get("user_name"),
            },
        )

    def post(self, request, id) -> HttpResponse | None:

        todo = get_object_or_404(Todo, pk=id)

        edit_form = TodoForm(request.POST)

        user_name = request.user_todo.get("user_name")
        if edit_form.is_valid():
            data = edit_form.cleaned_data
            todo.title = data.get("title", todo.title)
            todo.content = data.get("content", todo.content)
            todo.done = data.get("done", todo.done)
            todo.updated_at = timezone.now()
            todo.expired_at = data.get("expired_at", todo.expired_at)
            todo.save()
            return HttpResponseRedirect(redirect_to=reverse("todo_list:index"))

        return render(
            request,
            self.template_name,
            {
                "errors": edit_form.errors,
                "todo": {
                    **model_to_dict(todo),
                    "id": id,
                    "expired_at": todo.get_expired(),
                },
                "user_name": user_name,
            },
        )


class TodoDetails(DetailView):
    template_name = "todos/details.html"
    context_object_name = "todo"
    model = Todo

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_todo: dict = getattr(self.request, "user_todo")
        context["user_name"] = user_todo.get("user_name")
        return context


class TodoDelete(View):
    template_name = "todos/delete.html"
    context_object_name = "todo"

    def get(self, request, id) -> HttpResponse:
        todo = get_object_or_404(Todo, pk=id)
        user_todo = request.user_todo
        return render(
            request,
            self.template_name,
            {"todo": todo, "user_name": user_todo.get("user_name")},
        )

    def post(self, _, id) -> HttpResponse | None:
        todo = get_object_or_404(Todo, pk=id)
        todo.deleted_at = timezone.now()
        todo.save()
        return HttpResponseRedirect(redirect_to=reverse("todo_list:index"))


class UserCreate(View):
    template_name = "todos/user_account.html"
    context_object_name = "user"

    def get(self, request) -> HttpResponse:
        return render(request, self.template_name)

    def post(self, request) -> HttpResponse | None:

        user_form = UserForm(request.POST)

        try:
            if user_form.is_valid():

                data = user_form.cleaned_data

                # create user after
                user = UserTodo(**data)

                # init 2f auht and reset password
                f_auth = FactorAuth()
                r_password = ResetPassword()
                f_auth.user = user
                r_password.user = user

                # set code activation
                user.code = get_code()

                # hash password with bcrypt
                password_hashed = bcrypt.hashpw(
                    str(data.get("password")).encode(), bcrypt.gensalt()
                )

                user.password = password_hashed.decode()

                user.save()
                f_auth.save()
                r_password.save()

                # send email
                send_mail(
                    subject="activation code account",
                    message="code activation account",
                    from_email=os.getenv("SMTP_USER"),
                    recipient_list=[user.email],
                    html_message=f"use this code : <b>{user.code}</b> to active your account.<br>",
                )

                messages.success(
                    request,
                    message="your account has been create successfully. Use this code in your email account to active your account",
                )

                return HttpResponseRedirect(
                    redirect_to=reverse("todo_list:todo_user_active_account")
                )
            else:
                return render(
                    request,
                    self.template_name,
                    {"errors": user_form.errors, "user": user_form},
                )
        except Exception as _:
            return render(
                request,
                self.template_name,
                {
                    "errors": {
                        **user_form.errors,
                        "user_message": "an error occured please try again",
                    },
                    "user": user_form,
                },
            )


class UserActiveAccount(View):
    template_name = "todos/user_active_account.html"
    context_object_name = "user"
    model = UserTodo

    def get(self, request) -> HttpResponse:
        return render(request, self.template_name)

    def post(self, request) -> HttpResponse | None:

        user_activation_form = UserActivationForm(request.POST)

        if user_activation_form.is_valid():

            data = user_activation_form.cleaned_data

            try:
                user = self.model.objects.get(code=data.get("code"))

                if user.actived:
                    return render(
                        request,
                        self.template_name,
                        {"errors": {"user_message": "your account already actived."}},
                    )
                else:
                    # hours count in the pass since the creation account for currentime
                    td = timezone.now() - user.updated_at
                    hours, _ = divmod(td.seconds, 3600)

                    if hours >= 1:
                        return render(
                            request,

todos/templates/todos/index.html
{% extends "../base.html" %}

{% load static %}


{% block css %}
	<style>
		nav {
			height: 63px;
			max-height: 63px;
		}
		li.add_todo {
			cursor: pointer;
		}
		.todos-list {
			height: calc(100vh - 63px);
			max-height: calc(100vh - 63px);
			overflow-y: auto;
		}
		.todos_done .list-group-item {
			background-color: lightgreen;
			/* color: #112A46; */
			color: #123;
		}
		.todo-actions .btn-show {
			background-color: #044B5B;
		}
		.todo_title {
			max-width: 100%;
			overflow: hidden;
			text-overflow: ellipsis;
		}
	</style>
{% endblock %}


{% block body %}
	<div class="container-fluid text-white text-capitalize px-0">
		{% include "./navbar.html" with title="Todos list" %}
		<div class="todos-list d-flex justify-content-center text-black">
			{% if todos %}
				<div class="container-fluid">
					<div class="row h-100 justify-content-between">
						<div class="col-12 col-lg-6 px-0">
							{% if todos.todos_not_done %}
								<div class="todos_not_done pt-3">
									<h3 class="text-center">todos list created</h3>
									<ul class="list-group">
										{% for todo in todos.todos_not_done %}
											<li class="list-group-item d-flex justify-content-between align-items-center todo_not_done m-2">
												<div class="container-fluid px-0">
													<div class="row justify-content-between align-items-center">
														<div class="col-12 col-sm-8">
															<div class="todo_title">{{todo.title}}</div>
														</div>
														<div class="col-12 col-sm-4">
															<div class="todo-actions d-flex d-flex justify-content-start justify-content-sm-end">
																<a class="mx-1" href="{% url 'todo_list:edit_todo' todo.id %}">
																	<div class="todo_action btn btn-primary text-white">edit</div>
																</a>
																<a class="mx-1" href="{% url 'todo_list:details_todo' todo.id %}">
																	<div class="todo_action btn btn-show text-white">show</div>
																</a>
																<a class="mx-1" href="{% url 'todo_list:delete_todo' todo.id %}">
																	<div class="todo_action btn btn-danger text-white">delete</div>
																</a>
															</div>
														</div>
													</div>
												</div>
											</li>
										{% endfor %}
									</ul>
								</div>
							{% else %}
								<div class="container-fluid h-100">
									<div class="row align-items-center h-100 justify-content-center">
										<div class="no-todos col-12">
											<p class="text-center">yours todos created will be appear here</p>
										</div>
									</div>
								</div>
							{% endif %}

						</div>
						<div class="col-12 col-lg-6 px-0">
							<div class="border-start h-100">
								{% if todos.todos_done %}
									<div class="todos_done pt-3">
										<h3 class="text-center">todos list completed</h3>
										<ul class="list-group todos_done">
											{% for todo in todos.todos_done %}
												<li class="list-group-item d-flex justify-content-between align-items-center m-2 todo_done fw-bolder">
													<div class="container-fluid px-0">
														<div class="row justify-content-between align-items-center">
															<div class="col-12 col-sm-8">
																<div class="todo_title">{{todo.title}}</div>
															</div>
															<div class="col-12 col-sm-4">
																<div class="todo-actions d-flex justify-content-start justify-content-sm-end">

																	<a class="mx-1" href="{% url 'todo_list:edit_todo' todo.id %}">
																		<div class="todo_action btn btn-primary text-white">edit</div>
																	</a>
																	<a class="mx-1" href="{% url 'todo_list:details_todo' todo.id %}">
																		<div class="todo_action btn btn-show text-white">show</div>
																	</a>
																	<a class="mx-1" href="{% url 'todo_list:delete_todo' todo.id %}">
																		<div class="todo_action btn btn-danger text-white">delete</div>
																	</a>
																</div>
															</div>
														</div>
													</div>
												</li>
											{% endfor %}
										</ul>
									</div>
								{% else %}
									<div class="container-fluid h-100">
										<div class="row align-items-center h-100 justify-content-center">
											<div class="no-todos col-12">
												<p class="text-center">your todos done will be appear here</p>
											</div>
										</div>
									</div>
								{% endif %}

							</div>
						</div>

					</div>
				</div>
			{% else %}
				<div class="container-fluid h-100">
					<div class="row align-items-center h-100 justify-content-center align-items-center">
						<div class="no-todos col-12">
							<div class="no-todo-content d-flex flex-column justify-content-center">
								<p>You don't have à todos list</p>
								<a href="{% url 'todo_list:add_todo' %}">
									<div class="btn btn-success">add todo</div>
								</a>
							</div>
						</div>
					</div>
				</div>

			{% endif %}
		</div>
	</div>
{% endblock %}

todos/templates/todos/navbar.html
{% load static %}

<nav class="nav-bar-user bg-dark d-flex justify-content-between bg-dark align-items-center p-2">

	<div class="nav-brand">
		<a href="{% url 'todo_list:index' %}" class="text-decoration-none">
			<img src="{% static "todos/images/brand.png"%}" width="35" alt="todo list"/>
		</a>
		<span class="text-capitalize text-white brand-name">{{title|default:"Todos list"}}</span>
	</div>
	<ul class="nav-bar-actions list-unstyled d-flex align-items-center mb-0">
		{% if user_name %}

			<li class="nav-item logout mx-2" title="{{user_name|upper}}">
				<span class="btn border border-0 btn-danger fw-bolder rounded-circle user-name">
					{{user_name|make_list|first}}
				</span>
			</li>

		{% endif %}

		<li class="nav-item logout mx-2" title="logout">
			<a class="btn btn-outline-success fw-bolder" href="{% url 'todo_list:logout' %}">
				log out
			</a>
		</li>
		<li class="nav-item add_todo" title="add todo">
			<a href="{% url 'todo_list:add_todo' %}">
				<img src="{% static 'todos/images/plus.png'%}" width="30" alt="add todo"/>
			</a>
		</li>
	</ul>
</nav>

todos/templates/todos/user_account.html
{% extends "../base.html" %}

{% load static %}

{% block css %}
	<style>
		input {
			text-transform: capitalize;
		}
		.container-wrapper {
			box-shadow: 0 0 10px 0 rgba(0, 0, 0, 0.24);
			border-radius: 20px;
		}
		body {
			overflow: hidden;
		}
		.errorlist > li {
			list-style-type: none;
			color: red;
		}
		.errorlist {
			padding-left: 0;
		}
	</style>
{% endblock %}


{% block body %}
	<div class="container-fluid text-black text-capitalize px-0">
		<div class="form-wrapper vh-100 vw-100 overflow-auto d-flex align-items-center justify-content-center">
			<div class="container-wrapper mx-4 py-3 w-100">

				<div class="container">
					<div class="row align-items-center">
						<div class="col-md-5 d-none d-md-block">
							<div class="todo-image">
								<img src="{% static 'todos/images/user_register.png'%}" class="w-75" alt="user_login_logo">
							</div>
						</div>
						<div class="col-12 col-md-7">
							<form action="{% url 'todo_list:todo_user_account' %}" method="post" class="user_form w-100 text-capitalize p-3">
								{% if errors.user_message %}
									<div class="alert alert-danger">
										{{errors.user_message}}
									</div>
								{% endif %}

								<h2 class="text-center">user account</h2>
								<div class="form-group mb-3">
									<label for="first_name">first name</label>
									<input required type="text" name="first_name" value="{{user.first_name.value}}" id="first_name" class="form-control" placeholder="your first name" autofocus/>


									{% if errors.first_name %}
										<small class="text-danger">
											{{errors.first_name}}
										</small>
									{% endif %}
								</div>
								<div class="form-group mb-3">
									<label for="last_name">last name</label>
									<input required type="text" name="last_name" value="{{user.last_name.value}}" id="last_name" class="form-control" placeholder="your last name"/>


									{% if errors.last_name %}
										<small class="text-danger">
											{{errors.last_name}}
										</small>
									{% endif %}
								</div>

								<div class="form-group mb-3">
									<label for="email">email</label>
									<input required type="text" name="email" value="{{user.email.value}}" id="email" class="form-control" placeholder="your email"/>


									{% if errors.email %}
										<small class="text-danger">
											{{errors.email}}
										</small>
									{% endif %}
								</div>

								<div class="form-group mb-3">
									<label for="password">password</label>
									<input required type="password" name="password" value="{{user.password.value}}" id="password" class="form-control" placeholder="password"/>


									{% if errors.password %}
										<small class="text-danger">
											{{errors.password}}
										</small>
									{% endif %}
								</div>

								<div class="form-group mb-3">
									<label for="confirm_password">confirm password</label>
									<input required type="password" name="confirm_password" value="{{user.confirm_password.value}}" id="confirm_password" class="form-control" placeholder="confirm your password"/>


									{% if errors.confirm_password %}
										<small class="text-danger">
											{{errors.confirm_password}}
										</small>
									{% endif %}
								</div>

								<input required class="btn btn-primary w-100" type="submit" value="create account">
								<a class="mt-2 text-start w-100 d-block" href="{% url 'todo_list:todo_user_login' %}">
									You already have account ? log in to your account
								</a>
								{% csrf_token %}
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

todos/templates/todos/user_fact_auth.html
{% extends "../base.html" %}

{% load static %}

{% block css %}
	<style>
		input {
			text-transform: uppercase;
		}
		.container-wrapper {
			box-shadow: 0 0 10px 0 rgba(0, 0, 0, 0.24);
			border-radius: 20px;
		}
		body {
			overflow: hidden;
		}
		.errorlist > li {
			list-style-type: none;
			color: red;
		}
		.errorlist {
			padding-left: 0;
		}
	</style>
{% endblock %}


{% block body %}
	<div class="container-fluid text-black text-capitalize px-0">
		<div class="form-wrapper vh-100 vw-100 overflow-auto d-flex align-items-center justify-content-center">
			<div class="container-wrapper mx-4 py-3 w-100">

				<div class="container">
					<div class="row align-items-center">
						<div class="col-md-5 d-none d-md-block">
							<div class="todo-image">
								<img src="{% static 'todos/images/todo_active_account.png'%}" class="w-75" alt="user_verify_auth_logo">
							</div>
						</div>
						<div class="col-12 col-md-7">
							<form action="{% url 'todo_list:todo_user_fact_auth' %}" method="post" class="user_form w-100 text-capitalize p-3">
								<h2 class="text-center">verify your authentication</h2>
								{% if errors.user_message %}
									<div class="alert alert-danger">
										{{errors.user_message}}
									</div>
								{% elif messages %}
									{% for message in messages %}
										{% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
											<div class="alert alert-success">
												{{message}}
											</div>
										{% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
											<div class="alert alert-info">
												{{message}}
											</div>
										{% endif %}
									{% endfor %}
								{% endif %}
								<div class="form-group mb-3">
									<label for="code">enter your code</label>
									<input type="text" name="code" value="{{user.code.value}}" id="code" class="form-control" autocomplete="off" placeholder="xxxxx.." autofocus required/>
								</div>

								<input class="btn btn-primary w-100" type="submit" value="verify">
								<a class="mt-2 text-start w-100 d-block" href="{% url 'todo_list:todo_user_new_code_fact_auth' %}">
									no code received ? get new code
								</a>
								{% csrf_token %}
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

todos/templates/todos/user_login.html
{% extends "../base.html" %}

{% load static %}

{% block css %}
	<style>
		input {
			text-transform: capitalize;
		}
		.container-wrapper {
			box-shadow: 0 0 10px 0 rgba(0, 0, 0, 0.24);
			border-radius: 20px;
		}
		body {
			overflow: hidden;
		}
		.errorlist > li {
			list-style-type: none;
			color: red;
		}
		.errorlist {
			padding-left: 0;
		}
	</style>
{% endblock %}


{% block body %}
	<div class="container-fluid text-black text-capitalize px-0">
		<div class="form-wrapper d-flex align-items-center justify-content-center">
			<div class="container-wrapper mx-4 py-3 w-100">
				<div class="container">
					<div class="row align-items-center">
						<div class="col-md-5 d-none d-md-block">
							<div class="todo-image">
								<img src="{% static 'todos/images/user_login.png'%}" class="w-75" alt="user_register_secure">
							</div>
						</div>
						<div class="col-12 col-md-7">
							<form action="{% url 'todo_list:todo_user_login' %}" method="post" class="user_form w-100 text-capitalize p-3">
								<h2 class="text-center">user login</h2>
								{% if errors.user_message %}
									<div class="alert alert-danger">
										{{errors.user_message}}
									</div>
								{% elif messages %}
									{% for message in messages %}
										{% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
											<div class="alert alert-success">
												{{message}}
											</div>
										{% endif %}
									{% endfor %}
								{% endif %}
								<div class="form-group mb-3">
									<label for="email">enter your email</label>
									<input required type="email" name="email" value="{{user.email.value}}" id="email" class="form-control" placeholder="your email account" autofocus/>
								</div>

								<div class="form-group mb-3">
									<label for="password">enter your password</label>
									<input required type="password" name="password" value="{{user.password.value}}" id="password" class="form-control" autocomplete="off" placeholder="your password account"/>
								</div>

								<input required class="btn btn-primary w-100" type="submit" value="login">
								<a class="mt-2 text-start w-100 d-block" href="{% url 'todo_list:todo_user_account' %}">
									You don't have account ? create it
								</a>
								<a class="mt-2 text-start my-2 w-100 d-block" href="{% url 'todo_list:todo_user_reset_password' %}">
									forget your passord ? reset it
								</a>
								{% csrf_token %}
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}